#!/bin/bash
cd "`dirname \"$0\"`"
while [ ! -e run/make.pl ]; do pwd; cd ..; done
RUN=_C2014-$$
rm -rf _$RUN.tmp
mkdir _$RUN.tmp
cd _$RUN.tmp

for ror in 5.6 5.5 4.6
do
    perl ../run/make.pl -sqlite ../CDCM/Current/%-after163.yml ../CDCM/Data-2014-02/* -xdata='rules|template|%-ror-'$ror -xdata='1010|1|Financial and general assumptions|'$ror'e-2'
done

for ror in 5.5 4.6
do
    perl ../run/export.pl -base=ror-5.6 -dcp=ror-$ror -name=$ror'% rate of return'
done

cd ..
mv _$RUN.tmp $RUN.tmp
