#!/bin/sh
cd "`dirname \"$0\"`"
while [ ! -e pmod.pl ]; do pwd; cd ..; done
RUN=_edcm2013-$$
rm -rf _$RUN.tmp
mkdir _$RUN.tmp
pushd _$RUN.tmp
perl ../pmod.pl -sqlite -checksum -xdata='rules|transparency|1' ../EDCM/Current/%-beta*.yml ../EDCM/DCP-206/%-b206*.yml ../EDCM/Data-2013-02/*.yml
# perl ../pmod.pl /beta/ 11 45 46 47 48
# perl ../pmod.pl /b206/ 11 45 46 47 48
perl ../pmod.pl tscs 11 45 46 47 48
popd
mv _$RUN.tmp $RUN.tmp
echo "$RUN.tmp complete; press any key to exit"
read
