#!/bin/bash
cd "`dirname \"$0\"`"
while [ ! -e pmod.pl ]; do pwd; cd ..; done
RUN=_M2014-$$
rm -rf _$RUN.tmp
mkdir _$RUN.tmp
cd _$RUN.tmp
mkdir '~$models'

perl ../pmod.pl -sqlite ../ModelM/Current/%-*.yml ../ModelM/Previous/%-*.yml ../ModelM/Toys-2014/%-*.yml ../ModelM/Data-2014-02/*
perl ../pmod.pl tscs
perl ../pmod.pl /postDCP118/
for x in original postDCP071 postDCP096 postDCP118 indirectprop withtelecoms; do time ../pmod.pl /$x/ 1502; done

cd ..
mv _$RUN.tmp $RUN.tmp
