#/bin/sh
for tm in 2009-12
do
    tc=$tm
    for c in ModelM/Data-$tm*
        do
        pushd $c
        for m in *.yml
            do
            c=../../CDCM/Data-$tc/$m
            if [ -e $c ]
                then
                perl -MYAML -e '($m,$c)=map{YAML::LoadFile($_)}@ARGV;$m->{1399}=[@{$c->{1037}}[0,2..5]];YAML::DumpFile($ARGV[0],$m);' $m $c
            fi
        done
        popd
    done
done
