#!/bin/bash
cd "`dirname \"$0\"`"
while [ ! -e run/make.pl ]; do pwd; cd ..; done
RUN=_CP-$$
rm -rf _$RUN.tmp
mkdir _$RUN.tmp
cd _$RUN.tmp

time ../run/make.pl -xlsx ../CDCM/Current/%-clean132.yml ../CDCM/Data-2013-02/* ../CDCM/Data-2014-02/*
time ../run/import.pl -calc -sqlite *.xlsx
time ../run/export.pl -xlsx -dcp=2014-02 -base=2013-02
time ../run/export.pl -xlsx tscs

cd ..
mv _$RUN.tmp $RUN.tmp
