#!/bin/bash
cd "`dirname \"$0\"`"
while [ ! -e pmod.pl ]; do pwd; cd ..; done
RUN=_cdcmts-$$
rm -rf _$RUN.tmp
mkdir _$RUN.tmp
cd _$RUN.tmp
mkdir '~$models'
perl ../pmod.pl -pickbest -stats -sqlite ../CDCM/*/%-clean100.yml  ../CDCM/*/%-clean132.yml  ../CDCM/*/%-after163.yml ../CDCM/Data-*-02/*
perl ../pmod.pl tscs 10 37 38 39 40
cd ..
mv _$RUN.tmp $RUN.tmp
echo "$RUN.tmp complete; press any key to exit"
read
