#!/bin/bash
cd "`dirname \"$0\"`"
while [ ! -e run/make.pl ]; do pwd; cd ..; done
RUN=_dcp161-$$
rm -rf _$RUN.tmp
mkdir _$RUN.tmp
cd _$RUN.tmp

../run/make.pl -xlsx ../CDCM/Data-2014-02/UK* ../CDCM/Exceeded/%-base163.yml ../CDCM/Exceeded/%-dcp161unadd.yml
../run/import.pl -sqlite -calc *
../run/export.pl -xlsx -base=base163 -dcp=dcp161unadd -name='DCP 161 (cooked)' ../CDCM/Exceeded/+impact.yml -cdcmTariffImpact -cdcmRevenueMatrixImpact

cd ..
mv _$RUN.tmp $RUN.tmp
